### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by miraydamartinez** [jdejager89/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 1 (Does Not Meet Expectations)
* _Comment(s):_ 4 or more answers are missing text, query results (as supporting evidence), or the related queries. Conclusions are not well explained or supported by evidence. There is no powerpoint file with responses. 
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All queries accurately retrieve the data intended (as stated or implied by comments or the presentation).
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Queries are formatted according to the SQL lessons.
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 2 (Approaches Expectations)
* _Comment(s):_ Report demonstrates an insufficient understanding of funnels. Terms are used correctly throughout the report.

 ### Overall Score: 11/16
Nice job! Your project shows an in-depth understanding of SQL concepts and your code was clean and easy to read. I'm not sure if you accidentally attached the wrong powerpoint file but when I tried to open it up, it was just a blank template.

**Comment by jdejager89** [comment]
Can I try to submit the powerpoint again?
